<a href="https://colab.research.google.com/github/faizazulfqar/Machine-Learning/blob/master/Numpy_Basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Importing Numpy Library
import numpy as np

In [8]:
#creating Arrays
Array_1=np.array([7,4,0,2,9])
Array_2=np.array([6,3,9,1,7])
print(Array_1,Array_2)

[7 4 0 2 9] [6 3 9 1 7]


In [9]:
#Adding 2 Arrays
print(np.add(Array_1,Array_2))

[13  7  9  3 16]


In [12]:
#Subtracting 2 Arrays
print(np.subtract(Array_1,Array_2))

[ 1  1 -9  1  2]


In [13]:
#Multiplying 2 Arrays
print(np.multiply(Array_1,Array_2))

[42 12  0  2 63]


In [14]:
#Dividing 2 Arrays
print(np.divide(Array_1, Array_2))

[1.16666667 1.33333333 0.         2.         1.28571429]


In [15]:
#Dot Product of 2 Arrays
print(np.dot(Array_1,Array_2))

119


In [17]:
#To find a number on a specific Index
print(Array_1[3])

2


In [18]:
#Slicing of an Array
print(Array_1[3:5])

[2 9]


In [6]:
#Range of Numbers
Range_Array=np.arange(8)
print(Range_Array)

[0 1 2 3 4 5 6 7]


In [7]:
#Reshaping Array
Range_Array.reshape(2,4)

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [4]:
#Array of Zeros
Zeros_Array=np.zeros(5)
print(Zeros_Array)

[0. 0. 0. 0. 0.]


In [5]:
#Array of Ones
Ones_Array=np.ones(7)
print(Ones_Array)

[1. 1. 1. 1. 1. 1. 1.]


In [19]:
#Random Number Array (Float Numbers)
print(np.random.rand(8))

[0.65965506 0.64487456 0.95545137 0.55717306 0.05409124 0.9327645
 0.16196856 0.81465737]


In [33]:
#Random Number Array (Integer Numbers)
Random_Number=(np.random.randint(10,size=(2,5)))
print(Random_Number)

[[2 3 7 4 3]
 [9 0 1 8 6]]


In [36]:
#Flatten 2 Arrays
print(Random_Number.flatten())

[2 3 7 4 3 9 0 1 8 6]


In [37]:
#Transpose of Array
print(np.transpose(Random_Number))

[[2 9]
 [3 0]
 [7 1]
 [4 8]
 [3 6]]


In [31]:
#Create an Identity Matrix
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [39]:
#Concatenate two Arrays
print(np.concatenate((Array_1,Array_2)))

[7 4 0 2 9 6 3 9 1 7]


In [47]:
#Finding unique numbers in an array
Array_3=np.array([3,8,3,7,8,8,7])
print(Array_3)
print("Unique Numbers:", np.unique(Array_3))

[3 8 3 7 8 8 7]
Unique Numbers: [3 7 8]


In [45]:
#Sum along y-axis
Array_4=np.array([[15,22,9],[33,17,45]])
print(Array_4)
print("Sum:",np.sum(Array_4,axis=0))

[[15 22  9]
 [33 17 45]]
Sum: [48 39 54]


In [46]:
#Sum along x-axis
Array_4=np.array([[15,22,9],[33,17,45]])
print(Array_4)
print("Sum:",np.sum(Array_4,axis=1))

[[15 22  9]
 [33 17 45]]
Sum: [46 95]
